### PR TITLE
`spike_venn3` in new `spiketrain` module

### PR DESCRIPTION
**Pull request by chris-langfield**
For performing spike-level matching between different spike sorters.

The spike is binned in the sample and channel directions (customizable 2d bin size) and the number of spikes found in each bin by each spike sorter is transformed into the `"111", "101", ...` condition subsets needed for a 3-way venn diagram, without double counting.

### CODE REVIEW

**Review by oliche — CHANGES_REQUESTED** [review]
Hi Chris,

The tests run properly here and it's fast on generated data. 
The displays on the website are useful, thanks !

To release this you'd have to bump the version number and release the pypi package, I'd recommend doing this by creating a workflow through GitHub actions. This is minor.

I've setup automatic tests and it revealed a major flaw: we depend on brain box now due to this bincout2d function. It's not a dependency we want here.

Could you please refactor this by moving this `bincount2d` function into the `iblutils.numerical` module ? This only needs bumpy and it's generic enough to be there. You'd have to deprecate the use in brain box as well !

@k1o0

**Comment by chris-langfield** [comment]
Thinking to get this done via merging first https://github.com/int-brain-lab/iblutil/pull/19 and then https://github.com/int-brain-lab/ibllib/pull/622

@k1o0

**Comment by chris-langfield** [comment]
The tests have some instances of using `TemporaryNamedFile()` in a context manager, which doesn't play well with the Windows (this is now coming up because of the CI)

https://github.com/bravoserver/bravo/issues/111

Added the recommended fixes to the tests as part of this PR

**Comment by chris-langfield** [comment]
- Dependency on `iblutil` upgraded to the version containing `bincount2D` (1.7.0)
- PyPI workflow added

Ready for another look @oliche  Thanks!

**Review by oliche — APPROVED** [review]
Great, it would be nice to add in the readme the publication steps (ie. no need to publish by manually building en uploading to pypi).

Merging now !

**Pull request merged**
